// Define class that handles errors
export enum ErrorName {
  ERR_INTERNET_DISCONNECTED = "ERR_INTERNET_DISCONNECTED",
  ERR_INTERNAL_SERVER_ERROR = "ERR_INTERNAL_SERVER_ERROR",
}
export const CURRENT_USER_LOCATION_ID = -1;
export const CUSTOM_DESTINATION_LOCATION_ID = -2;
